server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        same-site: lax
        secure: false
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxx:3306/insight_plots?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 12345678
  # session 失效时间 30 天
  session:
    timeout: 2592000
    store-type: none
  # redis配置
  redis:
    port: 6379
    host: xxxx
    database: 1
    password: xxxx
  # rabbitmq 信息
  rabbitmq:
    host: xxxx
    password: xxxxxxx
    username: guest
    port: 5672
    listener:
      direct:
        acknowledge-mode: manual
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 要使用的模型ID
ai:
  model:
    model-id: 1660100329896673281
# 鱼聪明SDK
yuapi:
  client:
    access-key: xxx
    secret-key: xxxx
# 支付宝沙箱
pay:
  qrcodeurl: http://localhost:8080/api/alipay/tradeQuery?alipayAccountNo=%s
  alipay:
    APP_ID: xxxx
    APP_PRIVATE_KEY: xxx
    ALIPAY_PUBLIC_KEY: xxxxx